	const int countries_ln_c = 245;
	const wxString countries_ln[] = {
		wxT("Afghanistan"),
		wxT("Albania"),
		wxT("Algeria"),
		wxT("American Samoa"),
		wxT("Andorra"),
		wxT("Angola"),
		wxT("Anguilla"),
		wxT("Antarctica"),
		wxT("Antigua and Barbuda"),
		wxT("Argentina"),
		wxT("Armenia"),
		wxT("Aruba"),
		wxT("Australia"),
		wxT("Austria"),
		wxT("Azerbaijan"),
		wxT("Bahamas"),
		wxT("Bahrain"),
		wxT("Bangladesh"),
		wxT("Barbados"),
		wxT("Belarus"),
		wxT("Belgium"),
		wxT("Belize"),
		wxT("Benin"),
		wxT("Bermuda"),
		wxT("Bhutan"),
		wxT("Bolivia"),
		wxT("Bosnia and Herzegovina"),
		wxT("Botswana"),
		wxT("Bouvet Island"),
		wxT("Brazil"),
		wxT("British Indian Ocean Territory"),
		wxT("Brunei Darussalam"),
		wxT("Bulgaria"),
		wxT("Burkina Faso"),
		wxT("Burundi"),
		wxT("Cambodia"),
		wxT("Cameroon"),
		wxT("Canada"),
		wxT("Canada "),
		wxT("Cape Verde"),
		wxT("Cayman Islands"),
		wxT("Central African Republic"),
		wxT("Chad"),
		wxT("Chile"),
		wxT("China"),
		wxT("Christmas Island"),
		wxT("Cocos (Keeling) Islands"),
		wxT("Colombia"),
		wxT("Comoros"),
		wxT("Congo"),
		wxT("Cook Islands"),
		wxT("Costa Rica"),
		wxT("Cote D'Ivoire (Ivory Coast)"),
		wxT("Croatia (Hrvatska)"),
		wxT("Cuba"),
		wxT("Cyprus"),
		wxT("Czech Republic"),
		wxT("Czechoslovakia (former)"),
		wxT("Denmark"),
		wxT("Djibouti"),
		wxT("Dominica"),
		wxT("Dominican Republic"),
		wxT("East Timor"),
		wxT("Ecuador"),
		wxT("Egypt"),
		wxT("El Salvador"),
		wxT("Equatorial Guinea"),
		wxT("Eritrea"),
		wxT("Estonia"),
		wxT("Ethiopia"),
		wxT("Falkland Islands (Malvinas)"),
		wxT("Faroe Islands"),
		wxT("Fiji"),
		wxT("Finland"),
		wxT("France"),
		wxT("France, Metropolitan"),
		wxT("French Guiana"),
		wxT("French Polynesia"),
		wxT("French Southern Territories"),
		wxT("Gabon"),
		wxT("Gambia"),
		wxT("Georgia"),
		wxT("Germany"),
		wxT("Ghana"),
		wxT("Gibraltar"),
		wxT("Great Britain (UK)"),
		wxT("Greece"),
		wxT("Greenland"),
		wxT("Grenada"),
		wxT("Guadeloupe"),
		wxT("Guam"),
		wxT("Guatemala"),
		wxT("Guinea"),
		wxT("Guinea-Bissau"),
		wxT("Guyana"),
		wxT("Haiti"),
		wxT("Heard and McDonald Islands"),
		wxT("Honduras"),
		wxT("Hong Kong"),
		wxT("Hungary"),
		wxT("Iceland"),
		wxT("India"),
		wxT("Indonesia"),
		wxT("Iran"),
		wxT("Iraq"),
		wxT("Ireland"),
		wxT("Israel"),
		wxT("Italy"),
		wxT("Jamaica"),
		wxT("Japan"),
		wxT("Jordan"),
		wxT("Kazakhstan"),
		wxT("Kenya"),
		wxT("Kiribati"),
		wxT("Korea (North)"),
		wxT("Korea (South)"),
		wxT("Kuwait"),
		wxT("Kyrgyzstan"),
		wxT("Laos"),
		wxT("Latvia"),
		wxT("Lebanon"),
		wxT("Lesotho"),
		wxT("Liberia"),
		wxT("Libya"),
		wxT("Liechtenstein"),
		wxT("Lithuania"),
		wxT("Luxembourg"),
		wxT("Macau"),
		wxT("Macedonia"),
		wxT("Madagascar"),
		wxT("Malawi"),
		wxT("Malaysia"),
		wxT("Maldives"),
		wxT("Mali"),
		wxT("Malta"),
		wxT("Marshall Islands"),
		wxT("Martinique"),
		wxT("Mauritania"),
		wxT("Mauritius"),
		wxT("Mayotte"),
		wxT("Mexico"),
		wxT("Micronesia"),
		wxT("Moldova"),
		wxT("Monaco"),
		wxT("Mongolia"),
		wxT("Montserrat"),
		wxT("Morocco"),
		wxT("Mozambique"),
		wxT("Myanmar"),
		wxT("Namibia"),
		wxT("Nauru"),
		wxT("Nepal"),
		wxT("Netherlands"),
		wxT("Netherlands Antilles"),
		wxT("Neutral Zone"),
		wxT("New Caledonia"),
		wxT("New Zealand (Aotearoa)"),
		wxT("Nicaragua"),
		wxT("Niger"),
		wxT("Nigeria"),
		wxT("Niue"),
		wxT("Norfolk Island"),
		wxT("Northern Mariana Islands"),
		wxT("Norway"),
		wxT("Oman"),
		wxT("Pakistan"),
		wxT("Palau"),
		wxT("Panama"),
		wxT("Papua New Guinea"),
		wxT("Paraguay"),
		wxT("Peru"),
		wxT("Philippines"),
		wxT("Pitcairn"),
		wxT("Poland"),
		wxT("Portugal"),
		wxT("Puerto Rico"),
		wxT("Qatar"),
		wxT("Reunion"),
		wxT("Romania"),
		wxT("Russian Federation"),
		wxT("Rwanda"),
		wxT("S. Georgia and S. Sandwich Isls."),
		wxT("Saint Kitts and Nevis"),
		wxT("Saint Lucia"),
		wxT("Saint Vincent and the Grenadines"),
		wxT("Samoa"),
		wxT("San Marino"),
		wxT("Sao Tome and Principe"),
		wxT("Saudi Arabia"),
		wxT("Senegal"),
		wxT("Seychelles"),
		wxT("Sierra Leone"),
		wxT("Singapore"),
		wxT("Slovak Republic"),
		wxT("Slovenia"),
		wxT("Solomon Islands"),
		wxT("Somalia"),
		wxT("South Africa"),
		wxT("Spain"),
		wxT("Sri Lanka"),
		wxT("St. Helena"),
		wxT("St. Pierre and Miquelon"),
		wxT("Sudan"),
		wxT("Suriname"),
		wxT("Svalbard and Jan Mayen Islands"),
		wxT("Swaziland"),
		wxT("Sweden"),
		wxT("Switzerland"),
		wxT("Syria"),
		wxT("Taiwan"),
		wxT("Tajikistan"),
		wxT("Tanzania"),
		wxT("Thailand"),
		wxT("Togo"),
		wxT("Tokelau"),
		wxT("Tonga"),
		wxT("Trinidad and Tobago"),
		wxT("Tunisia"),
		wxT("Turkey"),
		wxT("Turkmenistan"),
		wxT("Turks and Caicos Islands"),
		wxT("Tuvalu"),
		wxT("Uganda"),
		wxT("Ukraine"),
		wxT("United Arab Emirates"),
		wxT("United Kingdom"),
		wxT("United States"),
		wxT("United States of America"),
		wxT("Uruguay"),
		wxT("US Minor Outlying Islands"),
		wxT("USSR (former)"),
		wxT("Uzbekistan"),
		wxT("Vanuatu"),
		wxT("Vatican City State (Holy See)"),
		wxT("Venezuela"),
		wxT("Viet Nam"),
		wxT("Virgin Islands (British)"),
		wxT("Virgin Islands (U.S.)"),
		wxT("Wallis and Futuna Islands"),
		wxT("Western Sahara"),
		wxT("Yemen"),
		wxT("Yugoslavia"),
		wxT("Zaire"),
		wxT("Zambia"),
		wxT("Zimbabwe")
	};
